
# define partitions for your network
bn_partitions:
    - 5
    - 5
    - 5
    - 5
    - 5
partitions:
    inputs:
        - [1,1,1,1,1]
    conv1.weight:
        - [1,1,1,1,1]
    layer1.0.conv1.weight:
        - [1,1,1,1,1]
    layer1.0.conv2.weight:
        - [1,1,1,1,1]
    layer2.0.conv1.weight:
        - [1,1,1,1,1]
    layer2.0.conv2.weight:
        - [1,1,1,1,1]
    hidden1.weight:
        - [1,1,1,1,1]
    hidden2.weight:
        - [1,1,1,1,1]
    hidden3.weight:
        - [1,1,1,1,1]
        
maps:
    conv1.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    layer1.0.conv1.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    layer1.0.conv2.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    layer2.0.conv1.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    layer2.0.conv2.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    hidden1.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    hidden2.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]
    hidden3.weight:
        - [0,1,1,1,1]
        - [1,0,1,1,1]
        - [1,1,0,1,1]
        - [1,1,1,0,1]
        - [1,1,1,1,0]